name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: simple
          package-name: openhasp-designer
          
      # Trigger builder workflow when a release is created
      - name: Trigger multi-arch build
        if: ${{ steps.release.outputs.release_created }}
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: release-created
          client-payload: '{"version": "${{ steps.release.outputs.tag_name }}"}'
